# Generated by Django 3.2.5 on 2021-07-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=40, verbose_name='Mark')),
                ('model', models.CharField(max_length=40, verbose_name='Model')),
                ('year', models.IntegerField(max_length=4, verbose_name='Year')),
                ('month', models.CharField(choices=[('Pet', 'Petrol'), ('Die', 'Diesel'), ('Ele', 'Electric'), ('CNG', 'CNG'), ('Hyb', 'Hybrid'), ('LPG', 'LPG')], max_length=3)),
            ],
        ),
    ]
