# Generated by Django 3.2.5 on 2021-07-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='month',
        ),
        migrations.AddField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(choices=[('Pet', 'Petrol'), ('Die', 'Diesel'), ('Ele', 'Electric'), ('CNG', 'CNG'), ('Hyb', 'Hybrid'), ('LPG', 'LPG')], default='Pet', max_length=3, verbose_name='Fuel_type'),
        ),
        migrations.AddField(
            model_name='cars',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Mileage'),
        ),
        migrations.AddField(
            model_name='cars',
            name='reg_number',
            field=models.CharField(default='null', max_length=10, verbose_name='Reg_number'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
    ]
